name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci

      # Set up Python environment
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false # 기본 환경 비활성화
          python-version: "3.12.6" # 원하는 Python 버전 설정

      # Create and activate Python virtual environment
      - name: Set up Python virtual environment
        run: |
          conda create --name conda --yes python=3.12.6 
          source activate conda

      # Install Python dependencies (if you have a requirements.txt file)
      - name: Install Python dependencies
        run: |
          source conda/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - run: pm2 restart BackendAPI
